package com.phcworld.mock;

import com.phcworld.user.domain.User;
import com.phcworld.user.service.port.UserRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeUserRepository implements UserRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<User> data = new ArrayList<>();
    @Override
    public Optional<User> findByEmail(String email) {
        return data.stream().filter(user -> user.getEmail().equals(email)).findAny();
    }

    @Override
    public Optional<User> findById(Long id) {
        return data.stream().filter(user -> user.getId().equals(id)).findAny();
    }

    @Override
    public User save(User user) {
        if(user.getId() == null || user.getId().equals(0L)){
            User newUser = User.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .email(user.getEmail())
                    .name(user.getName())
                    .password(user.getPassword())
                    .profileImage(user.getProfileImage())
                    .createDate(user.getCreateDate())
                    .authority(user.getAuthority())
                    .isDeleted(user.isDeleted())
                    .build();
            data.add(newUser);
            return newUser;
        } else {
            data.removeIf(u -> Objects.equals(u.getId(), user.getId()));
            data.add(user);
            return user;
        }
    }
}
