package com.phcworld.mock;

import com.phcworld.answer.domain.FreeBoardAnswer;
import com.phcworld.answer.service.port.FreeBoardAnswerRepository;
import com.phcworld.freeboard.domain.FreeBoard;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeFreeBoardAnswerRepository implements FreeBoardAnswerRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<FreeBoardAnswer> data = new ArrayList<>();
    @Override
    public Optional<FreeBoardAnswer> findById(Long id) {
        return data.stream().filter(freeBoardAnswer -> freeBoardAnswer.getId().equals(id)).findAny();
    }

    @Override
    public FreeBoardAnswer save(FreeBoardAnswer freeBoardAnswer) {
        if(freeBoardAnswer.getId() == null || freeBoardAnswer.getId().equals(0L)){
            FreeBoardAnswer newFreeBoardAnswer = FreeBoardAnswer.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .contents(freeBoardAnswer.getContents())
                    .writer(freeBoardAnswer.getWriter())
                    .freeBoard(freeBoardAnswer.getFreeBoard())
                    .createDate(freeBoardAnswer.getCreateDate())
                    .updateDate(freeBoardAnswer.getUpdateDate())
                    .isDeleted(freeBoardAnswer.isDeleted())
                    .build();
            data.add(newFreeBoardAnswer);
            return newFreeBoardAnswer;
        } else {
            data.removeIf(f -> Objects.equals(f.getId(), freeBoardAnswer.getId()));
            data.add(freeBoardAnswer);
            return freeBoardAnswer;
        }
    }
}
